version: '3.7'

services:
  regression:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_URL=${BASE_URL}
    volumes:
      - ./:/app/
    working_dir: /app

#    command: /bin/sh -c "ls -la && pytest  --alluredir=allure-result"
    command: pytest



