name: CI
on: push

env:
  BASE_URL: ${{secrets.BASE_URL}}

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Start Selenoid
      run: docker-compose up -d selenoid

    - name: Run tests
      run: docker-compose run tests

    - name: Generate Allure report
      run: docker-compose run tests allure generate --clean /app/allure-results

    - name: Deploy report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CI_TOKEN }}
        publish_dir: ./allure-results