name: Python application

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  BASE_URL: ${{secrets.BASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
#      - name: Checkout(copy) gh-pages repository to GutHub runner
#      - uses: actions/checkout@v2
#        with:
#          ref: gh-pages
#          path: ./.github/gh-pages
#          if delete

      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests
        run: |
          pytest --alluredir=allure-results 

      - name: Add allure information
        working-directory: allure-results
        if: always()
        run: |
          echo GIT_BRANCH=${{ github.head_ref || github.ref_name }}  >> environment.properties
          echo GIT_COMMIT_ID=${{ github.sha }} >> environment.properties
          echo GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD) >> environment.properties
          echo GIT_COMMIT_AUTHOR_NAME=$(git show -s --format='%ae' HEAD) >> environment.properties
          echo GIT_COMMIT_TIME=$(git show -s --format=%ci HEAD) >> environment.properties
          echo CHROME_VERSION=$(google-chrome --product-version) >> environment.properties
      - name: Allure results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.CI_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Generate report URL
        if: always()
        run: |
          echo "REPORT_URL=https://$GITHUB_REPOSITORY_OWNER.github.io/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER/" >> $GITHUB_ENV
      

      - uses: appleboy/telegram-action@master
        if: always()
        with:
          debug: true
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: |
            Ссылка на отчет: ${{ env.REPORT_URL }}


#      - name: Generate Allure Report URL
#        if: always()
#        id: generate-url
#        run: echo "ALLURE_REPORT_URL=https://${{ github.repository }}/gh-pages/" >> $GITHUB_ENV
#
#      - name: Send Telegram notification
#        if: always()
#        uses: appleboy/telegram-action@master
#        with:
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          to: ${{ secrets.TELEGRAM_TO }}
#          message: |
#            Отчет готов:
#
#            [Посмотреть отчет](${{ steps.generate-url.outputs.ALLURE_REPORT_URL }})
#
#            ${{ github.workflow }} успешно выполнен!

           
